### ISSUE TITLE
Swipe back gesture doesn't trigger `goBack()` function

### ISSUE THREAD

**Issue by Qrivi** [Rescado/rescado-app#2]
### Description

Using iOS' swipe back gesture to navigate back from `animal_detail_view` to `swipe_view` does not trigger the `goBack()` function in the former. As a result, if you like an animal on the detail view then going back still shows the same card. As a side result, opening the detail view again shows the heart as "non liked" and allows you to "like again".

Also, using the back button in the app bar to go back after liking an animal in the detail view results in a very glitchy animation.

### Steps to Reproduce

1. Go to the swipe tab and click on a card to view its details
2. Tap the heart to like the animal
3. Either click the back button -> glitchy animation
3. Or swipe back from the edge -> `goBack()` is not triggered

### Expected behavior

The `goBack()` method is triggered. If I liked the animal on the detail view and I go back, the next card should be shown and the animation should be smooth.

### Evidence

https://user-images.githubusercontent.com/3763638/140617997-9bc3c69d-3907-4dad-b0f2-92c373bff66b.mp4

### Environment

iPhone 12 Pro, iOS 15.1. Latest build from `develop` as of writing this issue.

**Comment by Pekket** [comment]
Same issue on Android

**Comment by Pekket** [comment]
On Android the solution is to use [WillPopScope](https://api.flutter.dev/flutter/widgets/WillPopScope-class.html) .
Unfortunately this disables the swipe back gesture on IOS. 😿

**Comment by Qrivi** [comment]
Then it is not a solution and I would even prefer `goBack()` to be triggered when you tap the like button on the detail page. Isn't it possible to on the swipe page verify which page was the previous page, and if it was the details page, read out whether or not the like button was pressed of some kind of state? But idk, if you pick this up I'll let you have a first look into it. I have no concrete suggestions.

**Comment by Qrivi** [comment]
Closing this issue. It won't be relevant anymore if PR #5 is merged featuring global state management instead of passing state from view to view when using `Navigator`. (🤢)

Also the work done on `work/swipeable-card` will feature a `SwipeController` or `CardController` to offer a global state on everything card related: the active card (useful to interact with and share between swipe view and detail view), the swipe status (useful to alter/animate the UI based on user input), last couple of cards (so there is always a card ready to be rendered), ... only good stuff.
